### ISSUE TITLE
Compatibility with xendit/xendit-ruby

### ISSUE THREAD

**Issue by kwhandy** [bekicot/xendit-rails#26]
Punten kang, saya barusan nyoba gabungin gem akang ini sm gem official xendit-ruby tp pas saya coba call buat bikin invoice pake module xendit-ruby tp module nya conflict kang. Nama module nya sama, jadi pas saya call `Xendit.api_keys` langsung error. Ada saran untuk handle ini ga?

**Comment by fwttnnn** [comment]
@kwhandy 

https://www.rubyguides.com/2018/11/ruby-alias-keyword/
https://medium.com/rubycademy/alias-in-ruby-bf89be245f69

**Comment by kwhandy** [comment]
> @kwhandy
> 
> https://www.rubyguides.com/2018/11/ruby-alias-keyword/ https://medium.com/rubycademy/alias-in-ruby-bf89be245f69

makasih mas @youkwhd issue sudah solved dari beberapa hari lalu. maksud saya kemarin biar integrated sm official gem dari xendit tanpa configurasi tambahan seperti ini. syukur-syukur kalo yg official mau merge sekalian:D
